title: Sean Buckle
description: Front-end development
url: https://seanbuckle.com
enforce_ssl: seanbuckle.com
markdown: kramdown
highlighter: pygments.rb # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
timezone: Europe/London
github_username:  seanbuckle
plugins: 
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
paginate: 5
future: true
permalink: pretty
