// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layouts from "./routes/_layouts.tsx";
import * as $api_projects from "./routes/api/projects.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Experience from "./islands/Experience.tsx";
import * as $Projects from "./islands/Projects.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layouts.tsx": $_layouts,
    "./routes/api/projects.ts": $api_projects,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Experience.tsx": $Experience,
    "./islands/Projects.tsx": $Projects,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
